name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone OpenWrt source code
      working-directory: /workdir
      run: |
        git clone https://github.com/openwrt/openwrt -b v24.10.0-rc2 openwrt

    - name: Copy .vermagic file to the OpenWrt build directory
      working-directory: /workdir/openwrt
      run: |
        cp $GITHUB_WORKSPACE/.vermagic /workdir/openwrt/.vermagic
        ls > 1.txt
        cat 1.txt

    - name: Modify include/kernel-defaults.mk
      working-directory: /workdir/openwrt
      run: |
        # 修改 include/kernel-defaults.mk 文件
        sed -i -e 's/^\(.\).*vermagic$/\1cp $(TOPDIR)\/.vermagic $(LINUX_DIR)\/.vermagic/' include/kernel-defaults.mk
        cat include/kernel-defaults.mk
